GET http://localhost:4000/schedules/1

###
POST http://localhost:4000/schedules
Content-Type: application/json

{
    "title": "운동 가기",
    "color": "#ffffff",
    "memo": "헬스가기",
    "isAllDay": true,
    "startDate": "2024-08-23T15:37:58.469Z",
    "endDate": "2024-08-23T15:37:58.469Z",
    "userId": 1
}

###
PATCH http://localhost:4000/schedules/7
Content-Type: application/json

{
   "memo": "가슴 운동 하기"
}

###
DELETE http://localhost:4000/schedules/7